import type { LLMProvider } from "./interface.js";
import { ProviderError, type LLMContentBlock, type LLMRequest, type LLMResponse, type LLMStreamEvent, type ModelCapability, type ProviderModel, type TokenUsage } from "./types.js";

function usageOf(value: any): TokenUsage { const inputTokens = value?.promptTokenCount ?? 0; const outputTokens = value?.candidatesTokenCount ?? 0; return { inputTokens, outputTokens, totalTokens: value?.totalTokenCount ?? inputTokens + outputTokens }; }
function partsOf(data: any): { content: LLMContentBlock[]; toolCalls: LLMResponse["toolCalls"] } { const content: LLMContentBlock[] = []; const toolCalls: LLMResponse["toolCalls"] = []; for (const part of data?.candidates?.[0]?.content?.parts ?? []) { if (part.text) content.push({ type: "text", text: part.text }); if (part.functionCall) { const call = { id: `gemini-tool-${toolCalls.length + 1}`, name: part.functionCall.name, arguments: part.functionCall.args ?? {} }; toolCalls.push(call); content.push({ type: "tool_call", toolCall: call }); } } return { content, toolCalls }; }

export class GeminiProvider implements LLMProvider {
  public readonly id = "gemini" as const;
  public readonly displayName = "Google Gemini";
  private readonly apiKey?: string;
  private readonly baseUrl: string;
  private readonly defaultModel: string;
  public constructor(apiKey = process.env.GEMINI_API_KEY, baseUrl = process.env.GEMINI_BASE_URL ?? "https://generativelanguage.googleapis.com/v1beta") { this.apiKey = apiKey; this.baseUrl = baseUrl.replace(/\/$/, ""); this.defaultModel = process.env.GEMINI_MODEL ?? "gemini-2.0-flash"; }
  public get configured(): boolean { return Boolean(this.apiKey); }
  private requireKey(): string { if (!this.apiKey) throw new ProviderError("Google Gemini API key is missing.", { provider: this.id, retryable: false, code: "missing_api_key" }); return this.apiKey; }
  private async request(path: string, init: RequestInit = {}): Promise<Response> { const joiner = path.includes("?") ? "&" : "?"; const response = await fetch(`${this.baseUrl}${path}${joiner}key=${encodeURIComponent(this.requireKey())}`, { ...init, headers: { "content-type": "application/json", ...(init.headers ?? {}) } }); if (!response.ok) { const body = await response.text(); throw new ProviderError(`Google Gemini request failed (${response.status}): ${body.slice(0, 300)}`, { provider: this.id, status: response.status, retryable: response.status === 408 || response.status === 429 || response.status >= 500, code: `http_${response.status}` }); } return response; }
  public async listModels(): Promise<ProviderModel[]> { const response = await this.request("/models"); const data = await response.json() as { models?: Array<{ name: string; displayName?: string; inputTokenLimit?: number; outputTokenLimit?: number; supportedGenerationMethods?: string[] }> }; return (data.models ?? []).filter((model) => model.supportedGenerationMethods?.includes("generateContent")).map((model) => ({ id: model.name.replace(/^models\//, ""), provider: this.id, displayName: model.displayName ?? model.name, contextWindow: model.inputTokenLimit, maxOutputTokens: model.outputTokenLimit, capabilities: ["coding", "reasoning", "research", "fast", "tools", "streaming"] })); }
  private body(request: LLMRequest): Record<string, unknown> { const contents = request.messages.filter((message) => message.role !== "system").map((message) => ({ role: message.role === "assistant" ? "model" : "user", parts: [{ text: typeof message.content === "string" ? message.content : message.content.filter((block) => block.type === "text").map((block) => block.text ?? "").join("\n") }] })); return { ...(request.system ? { systemInstruction: { parts: [{ text: request.system }] } } : {}), contents, generationConfig: { ...(request.maxOutputTokens ? { maxOutputTokens: request.maxOutputTokens } : {}) } }; }
  public async generate(request: LLMRequest): Promise<LLMResponse> { const model = request.model ?? this.defaultModel; const response = await this.request(`/models/${encodeURIComponent(model)}:generateContent`, { method: "POST", body: JSON.stringify(this.body(request)) }); const data = await response.json() as any; const parts = partsOf(data); return { ...parts, usage: usageOf(data.usageMetadata), finishReason: data.candidates?.[0]?.finishReason === "MAX_TOKENS" ? "length" : parts.toolCalls.length ? "tool_use" : "stop", provider: this.id, model, requestId: data.responseId }; }
  public async *stream(request: LLMRequest): AsyncIterable<LLMStreamEvent> { const result = await this.generate(request); for (const block of result.content) { if (block.text) yield { type: "text", text: block.text }; if (block.toolCall) yield { type: "tool_start", tool: block.toolCall }; } yield { type: "usage", usage: result.usage }; yield { type: "done", reason: result.finishReason }; }
  public supports(capability: ModelCapability): boolean { return ["coding", "reasoning", "research", "fast", "tools", "streaming"].includes(capability); }
}
