import type { LLMProvider } from "./interface.js";
import { ProviderError, type FinishReason, type LLMContentBlock, type LLMRequest, type LLMResponse, type LLMStreamEvent, type ModelCapability, type NormalizedToolCall, type ProviderId, type ProviderModel, type TokenUsage } from "./types.js";

type ChatResponse = { id?: string; model?: string; choices?: Array<{ message?: { content?: string | null; tool_calls?: Array<{ id?: string; function?: { name?: string; arguments?: string } }> }; finish_reason?: string }>; usage?: { prompt_tokens?: number; completion_tokens?: number; total_tokens?: number } };

function textOf(content: string | null | undefined): string { return content ?? ""; }
function finishReason(value: string | undefined): FinishReason { return value === "tool_calls" ? "tool_use" : value === "length" ? "length" : value === "stop" ? "stop" : "unknown"; }
function usageOf(usage: ChatResponse["usage"]): TokenUsage { const inputTokens = usage?.prompt_tokens ?? 0; const outputTokens = usage?.completion_tokens ?? 0; return { inputTokens, outputTokens, totalTokens: usage?.total_tokens ?? inputTokens + outputTokens }; }
function toolCallsOf(value: ChatResponse["choices"]): NormalizedToolCall[] { return (value?.[0]?.message?.tool_calls ?? []).map((call, index) => { let args: Record<string, unknown> = {}; try { args = JSON.parse(call.function?.arguments ?? "{}"); } catch { /* malformed provider output stays visible as an empty call */ } return { id: call.id ?? `tool-${index + 1}`, name: call.function?.name ?? "unknown", arguments: args }; }); }
function toOpenAIMessage(message: LLMRequest["messages"][number]): Record<string, unknown> { const content = typeof message.content === "string" ? message.content : message.content.filter((block) => block.type === "text").map((block) => block.text ?? "").join("\n"); return { role: message.role === "tool" ? "tool" : message.role, content, ...(message.name ? { name: message.name } : {}), ...(message.toolCallId ? { tool_call_id: message.toolCallId } : {}) }; }

export interface OpenAICompatibleOptions { id: ProviderId; displayName: string; apiKey?: string; baseUrl: string; defaultModel: string; extraHeaders?: Record<string, string>; }

export class OpenAICompatibleProvider implements LLMProvider {
  public readonly id: ProviderId;
  public readonly displayName: string;
  private readonly apiKey?: string;
  private readonly baseUrl: string;
  private readonly defaultModel: string;
  private readonly extraHeaders: Record<string, string>;

  public constructor(options: OpenAICompatibleOptions) { this.id = options.id; this.displayName = options.displayName; this.apiKey = options.apiKey; this.baseUrl = options.baseUrl.replace(/\/$/, ""); this.defaultModel = options.defaultModel; this.extraHeaders = options.extraHeaders ?? {}; }
  public get configured(): boolean { return Boolean(this.apiKey); }
  private requireKey(): string { if (!this.apiKey) throw new ProviderError(`${this.displayName} API key is missing.`, { provider: this.id, retryable: false, code: "missing_api_key" }); return this.apiKey; }
  private async request(path: string, init: RequestInit = {}): Promise<Response> { const response = await fetch(`${this.baseUrl}${path}`, { ...init, headers: { authorization: `Bearer ${this.requireKey()}`, "content-type": "application/json", ...this.extraHeaders, ...(init.headers ?? {}) } }); if (!response.ok) { const body = await response.text(); throw new ProviderError(`${this.displayName} request failed (${response.status}): ${body.slice(0, 300)}`, { provider: this.id, status: response.status, retryable: response.status === 408 || response.status === 409 || response.status === 429 || response.status >= 500, code: `http_${response.status}` }); } return response; }
  public async listModels(): Promise<ProviderModel[]> { const response = await this.request("/models"); const data = await response.json() as { data?: Array<{ id: string; owned_by?: string }> }; return (data.data ?? []).map((model) => ({ id: model.id, provider: this.id, displayName: model.id, capabilities: ["coding", "reasoning", "research", "fast", "tools", "streaming", "structured-output"] })); }
  private body(request: LLMRequest, stream = false): Record<string, unknown> { const messages = [...(request.system ? [{ role: "system", content: request.system }] : []), ...request.messages.map(toOpenAIMessage)]; const tools = request.tools?.map((tool) => ({ type: "function", function: { name: tool.name, description: tool.description, parameters: tool.inputSchema } })); return { model: request.model ?? this.defaultModel, messages, ...(tools?.length ? { tools } : {}), ...(request.temperature === undefined ? {} : { temperature: request.temperature }), max_tokens: request.maxOutputTokens ?? 1024, ...(stream ? { stream: true, stream_options: { include_usage: true } } : {}) }; }
  public async generate(request: LLMRequest): Promise<LLMResponse> { const response = await this.request("/chat/completions", { method: "POST", body: JSON.stringify(this.body(request)) }); const data = await response.json() as ChatResponse; const text = textOf(data.choices?.[0]?.message?.content); const toolCalls = toolCallsOf(data.choices); const content: LLMContentBlock[] = text ? [{ type: "text", text }] : []; return { content, toolCalls, usage: usageOf(data.usage), finishReason: finishReason(data.choices?.[0]?.finish_reason), provider: this.id, model: data.model ?? request.model ?? this.defaultModel, requestId: data.id }; }
  public async *stream(request: LLMRequest): AsyncIterable<LLMStreamEvent> { const response = await this.request("/chat/completions", { method: "POST", body: JSON.stringify(this.body(request, true)) }); if (!response.body) { const result = await this.generate(request); for (const block of result.content) if (block.text) yield { type: "text", text: block.text }; yield { type: "usage", usage: result.usage }; yield { type: "done", reason: result.finishReason }; return; } const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; let finalUsage: TokenUsage = { inputTokens: 0, outputTokens: 0, totalTokens: 0 }; let reason: FinishReason = "stop"; const toolBuffers = new Map<string, { name: string; args: string }>(); const consume = (line: string): LLMStreamEvent[] => { if (!line.startsWith("data:")) return []; const raw = line.slice(5).trim(); if (!raw || raw === "[DONE]") return raw === "[DONE]" ? [{ type: "usage", usage: finalUsage }, { type: "done", reason }] : []; let data: any; try { data = JSON.parse(raw); } catch { return []; } const events: LLMStreamEvent[] = []; const choice = data.choices?.[0]; const delta = choice?.delta; if (delta?.content) events.push({ type: "text", text: delta.content }); if (choice?.finish_reason) reason = finishReason(choice.finish_reason); for (const call of delta?.tool_calls ?? []) { const id = call.id ?? `tool-${call.index ?? 0}`; const current = toolBuffers.get(id) ?? { name: "", args: "" }; if (call.function?.name) { current.name = call.function.name; events.push({ type: "tool_start", tool: { id, name: current.name, arguments: {} } }); } if (call.function?.arguments) { current.args += call.function.arguments; events.push({ type: "tool_delta", toolId: id, delta: call.function.arguments }); } toolBuffers.set(id, current); } if (data.usage) finalUsage = usageOf(data.usage); return events; }; while (true) { const { done, value } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split(/\r?\n/); buffer = lines.pop() ?? ""; for (const line of lines) for (const event of consume(line)) yield event; } if (buffer) for (const event of consume(buffer)) yield event; for (const id of toolBuffers.keys()) yield { type: "tool_end", toolId: id }; yield { type: "usage", usage: finalUsage }; yield { type: "done", reason }; }
  public supports(capability: ModelCapability): boolean { return ["coding", "reasoning", "research", "fast", "tools", "streaming", "structured-output"].includes(capability); }
}
